index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: front/index.html.twig

########################### TESTS ############################### 


test_index:
    path: /test
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: tests/index.html.twig

test_list:
    path: /test/list
    controller: App\Controller\MembresController::testList 

test_show:
    path: /test/show/{id}
    controller: App\Controller\MembresController::testShow 

test_new:
    path: /test/new
    controller: App\Controller\MembresController::testNew 

test_edit:
    path: /test/edit/{id}
    controller: App\Controller\MembresController::testEdit 

test_del:
    path: /test/del/{id}
    controller: App\Controller\MembresController::testDelete 
